from os import path
from time import time

from urllib3 import PoolManager
from json import dump, dumps, load, loads
from json.decoder import JSONDecodeError
from typing import Dict, List, Optional, Any, Iterable

from core.io_default_api import IODefaultAPI, terabox_hosts

DEFAULT_PARAMS = {
    'app_id': 250528,
    'web': 1,  # Detail level
    'channel': 'dubox',
    'clienttype': 0
}


class Files():

    def __init__(self):
        self._container: Dict[str, Any] = {}
        self._json: str = path.dirname(__file__) + '\\container.json'

    def add_new(self,
                file: Dict[str, Any] = None,
                files: Iterable[Dict[str, Any]] | Iterable = None) -> None:
        self._container[file['server_filename']] = file

        if files:
            list(map(self.add_new, files))

    def get_files(self):
        return self._container

    def export_json(self):
        with open(self._json, 'w') as file:
            dump(self._container, file, indent=4)

    def save_into_BD(self):
        raise NotImplementedError('Dolbaeb')

    def dumps(self):
        return dumps(self._container, indent=4)

    def null_check(self) -> bool:
        return not self._container

    def fs_ids(self):
        """ fs_ids need for get_download_urls """
        for key in self._container:
            yield self._container[key]['fs_id']

    def __str__(self) -> str:
        return f'len: {len(self._container)}, \nfiles:\n {', '.join(self._container.keys())}'

    def __repr__(self) -> Dict[str, Any]:
        return {'len': len(self._container), 'files': self._container.keys()}


class CloudFileManager():

    NDUS_EXAMPLE = {'Cookie': 'ndus='}

    def __init__(self, container: Files, ndus: Dict[str, str] = NDUS_EXAMPLE):
        self.__http = IODefaultAPI(host=terabox_hosts)
        self.container = container
        self.ndus = ndus
        # Лежит тут, но ndus может поменяться
        self.get_info()

    def file_cloud_repr(
            self,
            #ndus: Dict[str, str] = NDUS_EXAMPLE,
            order: str = 'time',
            desc: int = 0,
            num: int = 100,
            page: int = 1,
            dir_name: str = '/',
            export_json: bool = True) -> Files:
        """ Default web-request to file list in terabox | Not openapi """
        # Keep in mind, what developers may change they api's
        # self.get_info(ndus=ndus) Полезно, ведь ndus может меняться(не точно)

        fields: Dict[str, Any] = {
            'order': order,
            'desc': desc,
            'dir': dir_name,
            'num': num,
            'page': page,
            'showempty': 0,
        }
        fields.update(DEFAULT_PARAMS)

        response = self.__http.make_request('GET',
                                            '/api/list',
                                            token=self.ndus,
                                            headers={},
                                            fields=fields)
        serialized_resp: Dict = response.json()

        self._check_ndus_valid(serialized_response=serialized_resp)

        for ans in serialized_resp['list']:
            self.container.add_new(self._filter_dict(ans))

        # Useful in some situations, example, noSQL or local save, debug
        if export_json:
            self.container.export_json()

        return self.container

    def get_download_urls(
            self,
            #ndus: Dict[str, str] = NDUS_EXAMPLE,
            fid_list: str = None,
            sign: str = None,
            bdstoken: str = None):
        """ 
        Sign and bdstoken are automatically generated by the browser, 
        so you cannot get them from Python.
        """
        # self.get_info(ndus=ndus) Полезно, ведь ndus может меняться(не точно)

        if self.container.null_check():
            raise ValueError('Cant find file for download | Files is empty')

        fields: Dict[str, Any] = {
            'fidlist': [fid_list],
            'type': 'dlink',
            'vip': 2,
            'sign': sign,
            'timestamp': round(time()),
            'need_speed': 0,
            'bdstoken': bdstoken,
        }
        fields.update(DEFAULT_PARAMS)

        response = self.__http.make_request('GET',
                                            '/api/download',
                                            token=self.ndus,
                                            headers={},
                                            fields=fields)
        serialized_resp: Dict = response.json()

        self._check_ndus_valid(serialized_response=serialized_resp)

        return serialized_resp

    def get_info(
            self,
            #ndus: Dict[str, str] = NDUS_EXAMPLE,
            response_out: bool = False):
        """ need js interpretator for use this correct """
        response = self.__http.make_request('GET',
                                            '/api/home/info',
                                            token=self.ndus,
                                            headers={})
        
        try:
            serialized_resp: Dict = response.json()

            if response_out:
                return serialized_resp

            del serialized_resp
        except JSONDecodeError:
            raise ValueError('ndus in not valid')

    def _filter_dict(self, fdict: Dict[str, Any]) -> Dict[str, Any]:
        temp = {
            'fs_id': fdict['fs_id'],
            'size': fdict['size'],
            'thumbs': fdict['thumbs'],
            'md5': fdict['md5'],
            'server_filename': fdict['server_filename'],
        }
        return temp

    def _check_ndus_valid(self, serialized_response) -> None:
        if serialized_response['errno'] != 0:
            raise ValueError('ndus updated')
